create table if not exists public.paraplanner_assessment_submissions (
  id bigint generated by default as identity primary key,
  candidate_name text not null
    check (char_length(candidate_name) between 1 and 120),
  score integer not null check (score between 0 and 20),
  score_band text not null
    check (char_length(score_band) between 1 and 60),
  passed boolean not null check (passed = (score >= 16)),
  unanswered_count integer not null check (unanswered_count between 0 and 20),
  elapsed_seconds integer not null check (elapsed_seconds between 0 and 2400),
  timing_mode text not null check (timing_mode in ('q40', 'q60', 't40')),
  auto_submitted boolean not null default false,
  answers smallint[] not null
    check (cardinality(answers) = 20 and answers <@ array[-1, 0, 1, 2, 3]::smallint[]),
  submitted_at timestamptz not null default timezone('utc', now())
);

alter table public.paraplanner_assessment_submissions enable row level security;
revoke all on public.paraplanner_assessment_submissions from anon, authenticated;
revoke all on sequence public.paraplanner_assessment_submissions_id_seq from anon, authenticated;
