[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[dev]
  framework = "#static"
  publish = "dist"
  port = 8888

[build.environment]
  NODE_VERSION = "22"

[functions]
  node_bundler = "esbuild"
