create table if not exists public.bookkeeping_assessment_submissions (
  id bigint generated by default as identity primary key,
  session_id uuid not null,
  candidate_name text not null
    check (char_length(candidate_name) between 1 and 120),
  score integer not null
    check (score between 0 and 20),
  score_band text not null
    check (char_length(score_band) between 1 and 100),
  time_used_seconds integer[] not null
    check (cardinality(time_used_seconds) = 20),
  answers smallint[] not null
    check (cardinality(answers) = 20),
  submitted_at timestamptz not null default timezone('utc', now())
);
create unique index if not exists bookkeeping_assessment_submissions_session_id_key
  on public.bookkeeping_assessment_submissions (session_id);

alter table public.bookkeeping_assessment_submissions enable row level security;

drop policy if exists "Anyone can submit an assessment"
  on public.bookkeeping_assessment_submissions;

revoke all on public.bookkeeping_assessment_submissions from anon, authenticated;
revoke all on sequence public.bookkeeping_assessment_submissions_id_seq from anon, authenticated;
