create table public.bookkeeping_assessment_submissions (
  id bigint generated by default as identity primary key,
  candidate_name text not null
    check (char_length(candidate_name) between 1 and 120),
  score integer not null
    check (score between 0 and 20),
  score_band text not null
    check (char_length(score_band) between 1 and 100),
  time_used_seconds integer[] not null
    check (cardinality(time_used_seconds) = 20),
  answers smallint[] not null
    check (cardinality(answers) = 20),
  submitted_at timestamptz not null default timezone('utc', now())
);

alter table public.bookkeeping_assessment_submissions enable row level security;

create policy "Anyone can submit an assessment"
  on public.bookkeeping_assessment_submissions
  for insert
  to anon, authenticated
  with check (true);
