create table if not exists public.fpa_assessment_submissions (
  id bigint generated by default as identity primary key,
  session_id uuid not null,
  candidate_name text not null
    check (char_length(candidate_name) between 1 and 120),
  candidate_email text
    check (candidate_email is null or char_length(candidate_email) <= 254),
  score integer not null check (score between 0 and 20),
  passed boolean not null check (passed = (score >= 16)),
  elapsed_seconds integer not null check (elapsed_seconds between 0 and 2400),
  auto_submitted boolean not null default false,
  answers smallint[] not null
    check (cardinality(answers) = 20 and answers <@ array[-1, 0, 1, 2, 3]::smallint[]),
  submitted_at timestamptz not null default timezone('utc', now())
);
create unique index if not exists fpa_assessment_submissions_session_id_key
  on public.fpa_assessment_submissions (session_id);

alter table public.fpa_assessment_submissions enable row level security;
revoke all on public.fpa_assessment_submissions from anon, authenticated;
revoke all on sequence public.fpa_assessment_submissions_id_seq from anon, authenticated;
