create table public.leaderboard_attempts (
  id bigint generated by default as identity primary key,
  trainee_name text not null default 'Anonymous'
    check (char_length(trainee_name) between 1 and 80),
  case_id text not null
    check (char_length(case_id) between 1 and 80),
  case_title text not null
    check (char_length(case_title) between 1 and 160),
  accuracy_pct integer not null check (accuracy_pct between 0 and 100),
  time_seconds numeric(10, 2) not null check (time_seconds >= 0 and time_seconds <= 86400),
  submitted_at timestamptz not null default timezone('utc', now())
);

create index leaderboard_attempts_ranking_idx
  on public.leaderboard_attempts (accuracy_pct desc, time_seconds asc, submitted_at asc);

alter table public.leaderboard_attempts enable row level security;

create policy "Anyone can view leaderboard attempts"
  on public.leaderboard_attempts
  for select
  to anon, authenticated
  using (true);

create policy "Anyone can submit leaderboard attempts"
  on public.leaderboard_attempts
  for insert
  to anon, authenticated
  with check (true);
