create table if not exists public.quiz_attempts (
  id uuid primary key default gen_random_uuid(),
  candidate_name text not null,
  candidate_role text,
  total_score numeric not null,
  total_marks numeric not null,
  percentage numeric not null,
  passed boolean not null,
  elapsed_seconds numeric,
  section_scores jsonb,
  answers jsonb,
  submitted_at timestamptz not null default now()
);

create index if not exists idx_quiz_attempts_submitted_at
  on public.quiz_attempts (submitted_at desc);
create index if not exists idx_quiz_attempts_candidate_name
  on public.quiz_attempts (candidate_name);
alter table public.quiz_attempts enable row level security;

create table if not exists public.bookkeeping_assessment_submissions (
  id bigint generated by default as identity primary key,
  candidate_name text not null
    check (char_length(candidate_name) between 1 and 120),
  score integer not null
    check (score between 0 and 20),
  score_band text not null
    check (char_length(score_band) between 1 and 100),
  time_used_seconds integer[] not null
    check (cardinality(time_used_seconds) = 20),
  answers smallint[] not null
    check (cardinality(answers) = 20),
  submitted_at timestamptz not null default timezone('utc', now())
);
alter table public.bookkeeping_assessment_submissions enable row level security;
revoke all on public.bookkeeping_assessment_submissions from anon, authenticated;
revoke all on sequence public.bookkeeping_assessment_submissions_id_seq from anon, authenticated;

create table if not exists public.leaderboard_attempts (
  id bigint generated by default as identity primary key,
  trainee_name text not null default 'Anonymous'
    check (char_length(trainee_name) between 1 and 80),
  case_id text not null
    check (char_length(case_id) between 1 and 80),
  case_title text not null
    check (char_length(case_title) between 1 and 160),
  accuracy_pct integer not null check (accuracy_pct between 0 and 100),
  time_seconds numeric(10, 2) not null check (time_seconds >= 0 and time_seconds <= 86400),
  submitted_at timestamptz not null default timezone('utc', now())
);
create index if not exists leaderboard_attempts_ranking_idx
  on public.leaderboard_attempts (accuracy_pct desc, time_seconds asc, submitted_at asc);
alter table public.leaderboard_attempts enable row level security;
revoke all on public.leaderboard_attempts from anon, authenticated;
revoke all on sequence public.leaderboard_attempts_id_seq from anon, authenticated;

create table if not exists public.fpa_assessment_submissions (
  id bigint generated by default as identity primary key,
  candidate_name text not null
    check (char_length(candidate_name) between 1 and 120),
  candidate_email text
    check (candidate_email is null or char_length(candidate_email) <= 254),
  score integer not null check (score between 0 and 20),
  passed boolean not null check (passed = (score >= 16)),
  elapsed_seconds integer not null check (elapsed_seconds between 0 and 2400),
  auto_submitted boolean not null default false,
  answers smallint[] not null
    check (cardinality(answers) = 20 and answers <@ array[-1, 0, 1, 2, 3]::smallint[]),
  submitted_at timestamptz not null default timezone('utc', now())
);
alter table public.fpa_assessment_submissions enable row level security;
revoke all on public.fpa_assessment_submissions from anon, authenticated;
revoke all on sequence public.fpa_assessment_submissions_id_seq from anon, authenticated;

create table if not exists public.paraplanner_assessment_submissions (
  id bigint generated by default as identity primary key,
  candidate_name text not null
    check (char_length(candidate_name) between 1 and 120),
  score integer not null check (score between 0 and 20),
  score_band text not null
    check (char_length(score_band) between 1 and 60),
  passed boolean not null check (passed = (score >= 16)),
  unanswered_count integer not null check (unanswered_count between 0 and 20),
  elapsed_seconds integer not null check (elapsed_seconds between 0 and 2400),
  timing_mode text not null check (timing_mode in ('q40', 'q60', 't40')),
  auto_submitted boolean not null default false,
  answers smallint[] not null
    check (cardinality(answers) = 20 and answers <@ array[-1, 0, 1, 2, 3]::smallint[]),
  submitted_at timestamptz not null default timezone('utc', now())
);
alter table public.paraplanner_assessment_submissions enable row level security;
revoke all on public.paraplanner_assessment_submissions from anon, authenticated;
revoke all on sequence public.paraplanner_assessment_submissions_id_seq from anon, authenticated;
